buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:[6.0,6.2)'
    }
}
plugins {
    id 'net.minecraftforge.gradle' version '[6.0.18,6.2)'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:1.21.1-${project.forge_version}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        minecraft_version: project.minecraft_version,
        forge_version: project.forge_version,
        mod_version: project.mod_version
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}
